python debian

diff --git a/docker/web-and-data/Dockerfile b/docker/web-and-data/Dockerfile
--- a/docker/web-and-data/Dockerfile
+++ b/docker/web-and-data/Dockerfile
@@ -3,32 +3,25 @@
 # artifacts under the hood. It therefore currently makes more sense to have a
 # single image supporting both instead of moving the scripts out to a separate
 # container.
-FROM maven:3.5.4 as builder-java
+FROM maven:3.5.4 as build
 COPY $PWD /cbioportal
 WORKDIR /cbioportal
 RUN mvn -DskipTests clean install
 
-# Build python dependencies and cache them
-FROM python:3-alpine as base
+FROM python:3.7.3-slim-stretch 
 RUN mkdir -p /cbioportal
-WORKDIR /cbioportal
-# Add mysql
-RUN set -ex \
-    && apk add --no-cache --virtual .build-deps \
-            gcc \
-            libc-dev \
-            mysql-client \
-    && apk add --no-cache mariadb-dev \
-    && sed '/st_mysql_options options;/a unsigned int reconnect;' /usr/include/mysql/mysql.h -i.bkp 
 
-COPY --from=builder-java /cbioportal/requirements.txt /cbioportal/requirements.txt
-# install build and runtime dependencies
+# install MYSQL build and runtime dependencies
 # ignore update failures
-RUN pip3 install -r /cbioportal/requirements.txt
-# Add JRE
+RUN   apt-get update  \
+      && apt-get install -y --no-install-recommends \
+        gcc \
+        default-libmysqlclient-dev \
+        && apt-get autoremove \
+	&& rm -rf /var/lib/apt/lists/* 
+
 # Default to UTF-8 file.encoding
 ENV LANG C.UTF-8
-
 # add a simple script that can auto-detect the appropriate JAVA_HOME value
 # based on whether the JDK or only the JRE is installed
 RUN { \
@@ -38,26 +31,42 @@ RUN { \
 		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
 	} > /usr/local/bin/docker-java-home \
 	&& chmod +x /usr/local/bin/docker-java-home
-ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
-ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
+
+# do some fancy footwork to create a JAVA_HOME that's cross-architecture-safe
+RUN ln -svT "/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)" /docker-java-home
+ENV JAVA_HOME /docker-java-home/jre
 
 ENV JAVA_VERSION 8u212
-ENV JAVA_ALPINE_VERSION 8.212.04-r0
+ENV JAVA_DEBIAN_VERSION 8u212-b01-1~deb9u1
 
-RUN set -x \
-	&& apk add --no-cache \
-		openjdk8-jre="$JAVA_ALPINE_VERSION" \
-	&& [ "$JAVA_HOME" = "$(docker-java-home)" ]
+RUN set -ex; \
+	\
+# deal with slim variants not having man page directories (which causes "update-alternatives" to fail)
+	if [ ! -d /usr/share/man/man1 ]; then \
+		mkdir -p /usr/share/man/man1; \
+	fi; \
+	\
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		openjdk-8-jre="$JAVA_DEBIAN_VERSION" \
+	; \
+	rm -rf /var/lib/apt/lists/*;
+
+
+COPY --from=build /cbioportal/requirements.txt /cbioportal/requirements.txt
+RUN  pip3 install -r /cbioportal/requirements.txt
 
 
 # copy over core jar and scripts
-COPY --from=builder-java /cbioportal/core /cbioportal/core
-COPY --from=builder-java /cbioportal/scripts /cbioportal/scripts
+COPY --from=build /cbioportal/core /cbioportal/core
+COPY --from=build /cbioportal/scripts /cbioportal/scripts
+
 # add importer scripts to PATH for easy running in containers
-#RUN find /cbioportal/core/src/main/scripts/ -type f -name '*.pl'  -print0 | xargs -0 -- ln -sv /usr/local/bin
+RUN find /cbioportal/core/src/main/scripts/ -type f -executable \! -name '*.pl'  -print0 | xargs -0 -- ln -st /usr/local/bin
 
 # put config files in this folder if you want to override config
 ENV PORTAL_HOME=/cbioportal
 
 # TODO: fix the workdir-dependent references to '../scripts/env.pl' and do this:
 # RUN find $PWD/core/src/main/scripts/ -type f -executable \! \( -name env.pl -o -name envSimple.pl \)  -print0 | xargs -0 -- ln -st /usr/local/bin
+
